/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * The interface every codec implementation in the test bench is driven
 * through, whether it came from the driver or from candidates/.
 *
 * codecbench.py generates variants.gen.c, which fills in the registry: the
 * three driver variants (built from a verbatim copy of ploytec_codec.c with
 * different CONFIG_* defines) followed by each candidate. main() only ever
 * walks the registry, so adding an implementation needs no C changes here.
 *
 * (C) 2026 Frank van de Pol <fvdpol@gmail.com>
 */

#ifndef PLOYTEC_CODEC_IMPL_H
#define PLOYTEC_CODEC_IMPL_H

#include <linux/types.h>

/* Matches the driver's batch entry points exactly. */
typedef void (*ploytec_encode_fn)(u8 *dest, const u8 *src, const int n_frames);
typedef void (*ploytec_decode_fn)(u8 *dest, const u8 *src, const int n_frames);
typedef void (*ploytec_init_fn)(void);

enum ploytec_impl_kind {
	PLOYTEC_IMPL_DRIVER,		/* built from the real driver source */
	PLOYTEC_IMPL_CANDIDATE,		/* experimental, from candidates/ */
};

struct ploytec_codec_impl {
	const char *name;
	const char *description;
	enum ploytec_impl_kind kind;
	ploytec_init_fn init;		/* may be NULL */
	ploytec_encode_fn encode;
	ploytec_decode_fn decode;
};

/* Generated by codecbench.py into variants.gen.c */
extern const struct ploytec_codec_impl ploytec_impls[];
extern const unsigned int ploytec_impl_count;

/*
 * Name of the implementation used as the correctness oracle: the driver's
 * own portable reference codec. Generated alongside the registry.
 */
extern const char *ploytec_reference_impl;

#endif /* PLOYTEC_CODEC_IMPL_H */
