// SPDX-License-Identifier: GPL-2.0-or-later
/*
 *   ALSA driver for Reloop Jockey 3 devices
 *   KUnit tests for the Ploytec bit-plane codec
 *
 *   Copyright (c) 2026 by Frank van de Pol <fvdpol@gmail.com>
 */

/**
 * DOC: Proving the Ploytec codec correct
 *
 * ploytec_codec.c carries three implementations of one bit-scatter/gather
 * algorithm - a portable reference plus 32-bit and 64-bit SWAR variants that
 * use magic-multiplier tricks and 256-entry lookup tables. Exactly one is
 * compiled into any given build, chosen by CONFIG_64BIT and
 * CONFIG_SND_USB_JOCKEY3_REFERENCE_CODEC. The optimized paths are 4-10x
 * faster and are what every user actually runs, but they are not obviously
 * correct by inspection.
 *
 * These tests validate whichever variant the build selected, through the
 * public ploytec_encode_batch() / ploytec_decode_batch() entry points. No
 * symbols are exported and the codec is not modified to be testable; the
 * test object is simply linked into the same module.
 *
 * The strategy is stronger than sampling random inputs:
 *
 * 1. The oracle is a *declarative bit map* (ploytec_encode_map[] and
 *    ploytec_decode_map[] below), not a second copy of the driver's loops.
 *    Because it states the format as data rather than as control flow, a
 *    transcription error cannot propagate symmetrically into both.
 *
 * 2. The codec is a pure bit permutation, so as a function over GF(2) it is
 *    linear. ploytec_test_*_is_linear() establishes that linearity holds, and
 *    ploytec_test_*_permutation_complete() measures the map's action on every
 *    single basis vector. A linear map is *fully determined* by its action on
 *    the basis, so together those two cases pin down the result for all 2^96
 *    (encode) and 2^512 (decode) possible inputs.
 *
 *    The residual risk is a non-linearity that the sampled pairs happen to
 *    miss; the tests are not a formal proof, but they are far more than spot
 *    checks.
 *
 * 3. Golden vectors generated by an independent Python model of the format
 *    (tests/codec/ploytec_model.py) guard against the whole family drifting
 *    away from the wire format together.
 *
 * Randomized cases use a small seeded xorshift generator rather than the
 * kernel RNG, so every architecture exercises identical data and any failure
 * reproduces exactly.
 */

#include <kunit/test.h>
#include <linux/string.h>
#include "ploytec_codec.h"
#include "ploytec_codec_test_vectors.h"

/* Largest batch either direction is ever asked for, from jockey3.c */
#define PLOYTEC_TEST_MAX_ENCODE_FRAMES	PLOYTEC_PLAYBACK_FRAMES
#define PLOYTEC_TEST_MAX_DECODE_FRAMES	PLOYTEC_CAPTURE_FRAMES

/* How many random frames the sampling-based cases run through */
#define PLOYTEC_TEST_RANDOM_FRAMES	4096
#define PLOYTEC_TEST_LINEARITY_PAIRS	2048

/* Guard region used to catch writes outside the destination buffer */
#define PLOYTEC_TEST_GUARD		64
#define PLOYTEC_TEST_GUARD_BYTE		0xA5

/* Wire bytes the capture decoder must never read */
#define PLOYTEC_TEST_UNUSED0_START	0x18
#define PLOYTEC_TEST_UNUSED0_END	0x20
#define PLOYTEC_TEST_UNUSED1_START	0x38
#define PLOYTEC_TEST_UNUSED1_END	0x40

/*
 * The format, stated as data.
 *
 * Playback packs 4 channels into 48 wire bytes as two pairs: (ch0, ch2) in
 * bytes 0..23 and (ch1, ch3) in bytes 24..47. Each 24-byte block holds three
 * 8-byte planes ordered most-significant sample byte first. Within a plane,
 * wire byte i carries bit (7 - i) of the sample byte, and a channel's index
 * within its pair picks the bit of the wire byte it lands in.
 */
struct ploytec_encode_map_entry {
	u8 src_idx;	// byte of the 12-byte PCM frame
	u8 dst_base;	// first wire byte of the plane it scatters into
	u8 dst_bit;	// bit of each wire byte it occupies
};

static const struct ploytec_encode_map_entry ploytec_encode_map[] = {
	{  2,  0, 0 }, {  8,  0, 1 },	/* ch0 / ch2, most significant byte */
	{  1,  8, 0 }, {  7,  8, 1 },	/* ch0 / ch2, middle byte */
	{  0, 16, 0 }, {  6, 16, 1 },	/* ch0 / ch2, least significant byte */
	{  5, 24, 0 }, { 11, 24, 1 },	/* ch1 / ch3, most significant byte */
	{  4, 32, 0 }, { 10, 32, 1 },	/* ch1 / ch3, middle byte */
	{  3, 40, 0 }, {  9, 40, 1 },	/* ch1 / ch3, least significant byte */
};

/*
 * Capture unpacks 6 channels from 48 of the 64 wire bytes, as two groups of
 * three: group 0 at 0x00..0x17 holds ch0, ch2, ch4 and group 1 at
 * 0x20..0x37 holds ch1, ch3, ch5. Plane ordering matches playback, and a
 * channel's index within its group picks the bit of the wire byte it was
 * packed into. Wire bytes 0x18..0x1f and 0x38..0x3f carry nothing.
 */
struct ploytec_decode_map_entry {
	u8 dst_idx;	// byte of the 18-byte PCM frame
	u8 src_base;	// first wire byte of the plane it gathers from
	u8 src_bit;	// bit of each wire byte it was packed into
};

static const struct ploytec_decode_map_entry ploytec_decode_map[] = {
	{ 0x00, 0x10, 0 }, { 0x01, 0x08, 0 }, { 0x02, 0x00, 0 },	/* ch0 */
	{ 0x03, 0x30, 0 }, { 0x04, 0x28, 0 }, { 0x05, 0x20, 0 },	/* ch1 */
	{ 0x06, 0x10, 1 }, { 0x07, 0x08, 1 }, { 0x08, 0x00, 1 },	/* ch2 */
	{ 0x09, 0x30, 1 }, { 0x0A, 0x28, 1 }, { 0x0B, 0x20, 1 },	/* ch3 */
	{ 0x0C, 0x10, 2 }, { 0x0D, 0x08, 2 }, { 0x0E, 0x00, 2 },	/* ch4 */
	{ 0x0F, 0x30, 2 }, { 0x10, 0x28, 2 }, { 0x11, 0x20, 2 },	/* ch5 */
};

/**
 * ploytec_oracle_encode() - Encode one frame straight from the bit map
 * @dest: 48-byte destination buffer
 * @src: 12-byte source buffer
 */
static void ploytec_oracle_encode(u8 *dest, const u8 *src)
{
	memset(dest, 0, PLOYTEC_PLAYBACK_FRAME_SIZE);

	for (size_t e = 0; e < ARRAY_SIZE(ploytec_encode_map); e++) {
		const struct ploytec_encode_map_entry *m = &ploytec_encode_map[e];

		for (int i = 0; i < 8; i++)
			dest[m->dst_base + i] |=
				((src[m->src_idx] >> (7 - i)) & 1) << m->dst_bit;
	}
}

/**
 * ploytec_oracle_decode() - Decode one frame straight from the bit map
 * @dest: 18-byte destination buffer
 * @src: 64-byte source buffer
 */
static void ploytec_oracle_decode(u8 *dest, const u8 *src)
{
	memset(dest, 0, PLOYTEC_CAPTURE_PCM_FRAME_SIZE);

	for (size_t e = 0; e < ARRAY_SIZE(ploytec_decode_map); e++) {
		const struct ploytec_decode_map_entry *m = &ploytec_decode_map[e];

		for (int i = 0; i < 8; i++)
			dest[m->dst_idx] |=
				((src[m->src_base + i] >> m->src_bit) & 1) << (7 - i);
	}
}

/*
 * xorshift64*, mirrored bit-for-bit by tests/codec/ploytec_model.py so the
 * kernel tests and the user-space bench see identical data.
 */
struct ploytec_test_rng {
	u64 state;
};

static void ploytec_rng_init(struct ploytec_test_rng *rng, u64 seed)
{
	rng->state = seed ? seed : 1;
}

static u64 ploytec_rng_next(struct ploytec_test_rng *rng)
{
	u64 x = rng->state;

	x ^= x >> 12;
	x ^= x << 25;
	x ^= x >> 27;
	rng->state = x;

	return x * 0x2545F4914F6CDD1DULL;
}

static void ploytec_rng_fill(struct ploytec_test_rng *rng, u8 *buf, size_t len)
{
	size_t off = 0;

	while (off < len) {
		u64 v = ploytec_rng_next(rng);

		for (int i = 0; i < 8 && off < len; i++, off++)
			buf[off] = (v >> (i * 8)) & 0xFF;
	}
}

/* Is this wire byte one the capture decoder is allowed to read? */
static bool ploytec_capture_byte_used(int idx)
{
	if (idx >= PLOYTEC_TEST_UNUSED0_START && idx < PLOYTEC_TEST_UNUSED0_END)
		return false;
	if (idx >= PLOYTEC_TEST_UNUSED1_START && idx < PLOYTEC_TEST_UNUSED1_END)
		return false;

	return true;
}

/* Count set bits in a buffer, recording the position of the last one seen. */
static int ploytec_count_set_bits(const u8 *buf, size_t len, int *last_pos)
{
	int count = 0;

	for (size_t i = 0; i < len; i++) {
		for (int b = 0; b < 8; b++) {
			if (buf[i] & (1 << b)) {
				count++;
				if (last_pos)
					*last_pos = i * 8 + b;
			}
		}
	}

	return count;
}

/* --- Golden vectors from the independent Python model --------------------- */

static void ploytec_encode_vector_desc(const struct ploytec_encode_vector *v,
				       char *desc)
{
	strscpy(desc, v->name, KUNIT_PARAM_DESC_SIZE);
}

KUNIT_ARRAY_PARAM(ploytec_encode_vector, ploytec_encode_vectors,
		  ploytec_encode_vector_desc);

static void ploytec_decode_vector_desc(const struct ploytec_decode_vector *v,
				       char *desc)
{
	strscpy(desc, v->name, KUNIT_PARAM_DESC_SIZE);
}

KUNIT_ARRAY_PARAM(ploytec_decode_vector, ploytec_decode_vectors,
		  ploytec_decode_vector_desc);

static void ploytec_test_encode_known_vectors(struct kunit *test)
{
	const struct ploytec_encode_vector *v = test->param_value;
	u8 dest[PLOYTEC_PLAYBACK_FRAME_SIZE];

	memset(dest, 0xFF, sizeof(dest));
	ploytec_encode_batch(dest, v->src, 1);

	KUNIT_EXPECT_MEMEQ_MSG(test, dest, v->expect, sizeof(dest),
			       "encode of vector '%s' does not match the model",
			       v->name);
}

static void ploytec_test_decode_known_vectors(struct kunit *test)
{
	const struct ploytec_decode_vector *v = test->param_value;
	u8 dest[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];

	memset(dest, 0xFF, sizeof(dest));
	ploytec_decode_batch(dest, v->src, 1);

	KUNIT_EXPECT_MEMEQ_MSG(test, dest, v->expect, sizeof(dest),
			       "decode of vector '%s' does not match the model",
			       v->name);
}

/* --- Agreement with the declarative bit map ------------------------------- */

static void ploytec_test_encode_matches_oracle(struct kunit *test)
{
	u8 src[PLOYTEC_PLAYBACK_PCM_FRAME_SIZE];
	u8 got[PLOYTEC_PLAYBACK_FRAME_SIZE];
	u8 want[PLOYTEC_PLAYBACK_FRAME_SIZE];
	struct ploytec_test_rng rng;

	ploytec_rng_init(&rng, 0x0123456789ABCDEFULL);

	for (int t = 0; t < PLOYTEC_TEST_RANDOM_FRAMES; t++) {
		ploytec_rng_fill(&rng, src, sizeof(src));

		/* Prefill with noise so a short write is visible. */
		memset(got, 0x5A, sizeof(got));
		ploytec_encode_batch(got, src, 1);
		ploytec_oracle_encode(want, src);

		KUNIT_ASSERT_MEMEQ_MSG(test, got, want, sizeof(got),
				       "encode disagrees with the bit map at iteration %d",
				       t);
	}
}

static void ploytec_test_decode_matches_oracle(struct kunit *test)
{
	u8 src[PLOYTEC_CAPTURE_FRAME_SIZE];
	u8 got[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	u8 want[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	struct ploytec_test_rng rng;

	ploytec_rng_init(&rng, 0x0123456789ABCDEFULL);

	for (int t = 0; t < PLOYTEC_TEST_RANDOM_FRAMES; t++) {
		ploytec_rng_fill(&rng, src, sizeof(src));

		memset(got, 0x5A, sizeof(got));
		ploytec_decode_batch(got, src, 1);
		ploytec_oracle_decode(want, src);

		KUNIT_ASSERT_MEMEQ_MSG(test, got, want, sizeof(got),
				       "decode disagrees with the bit map at iteration %d",
				       t);
	}
}

/* --- The map is a complete, injective bit permutation --------------------- */

/*
 * Encode: feed a one-hot input for each of the 96 input bits. Each must land
 * on exactly one output bit, at the position the map predicts, and no two
 * inputs may collide. That determines the map's action on every basis vector.
 */
static void ploytec_test_encode_permutation_complete(struct kunit *test)
{
	u8 src[PLOYTEC_PLAYBACK_PCM_FRAME_SIZE];
	u8 dest[PLOYTEC_PLAYBACK_FRAME_SIZE];
	DECLARE_BITMAP(seen, PLOYTEC_PLAYBACK_FRAME_SIZE * 8);
	int covered = 0;

	bitmap_zero(seen, PLOYTEC_PLAYBACK_FRAME_SIZE * 8);

	for (int byte = 0; byte < PLOYTEC_PLAYBACK_PCM_FRAME_SIZE; byte++) {
		for (int bit = 0; bit < 8; bit++) {
			int pos = -1, count, want_pos = -1;

			memset(src, 0, sizeof(src));
			src[byte] = 1 << bit;

			memset(dest, 0, sizeof(dest));
			ploytec_encode_batch(dest, src, 1);

			count = ploytec_count_set_bits(dest, sizeof(dest), &pos);
			KUNIT_ASSERT_EQ_MSG(test, count, 1,
					    "src[%d] bit %d set %d output bits, expected 1",
					    byte, bit, count);

			/* Where the bit map says it should have landed. */
			for (size_t e = 0; e < ARRAY_SIZE(ploytec_encode_map); e++) {
				const struct ploytec_encode_map_entry *m =
					&ploytec_encode_map[e];

				if (m->src_idx == byte)
					want_pos = (m->dst_base + (7 - bit)) * 8 +
						   m->dst_bit;
			}

			KUNIT_ASSERT_EQ_MSG(test, pos, want_pos,
					    "src[%d] bit %d landed at output bit %d, map says %d",
					    byte, bit, pos, want_pos);
			KUNIT_ASSERT_FALSE_MSG(test, test_bit(pos, seen),
					       "output bit %d is written by two different input bits",
					       pos);
			__set_bit(pos, seen);
			covered++;
		}
	}

	KUNIT_EXPECT_EQ(test, covered, PLOYTEC_PLAYBACK_PCM_FRAME_SIZE * 8);
}

/*
 * Decode: sweep all 512 input bits. The 144 meaningful ones must each land on
 * a distinct output bit; every other input bit must be ignored entirely, which
 * checks the unused byte ranges and unused bits in the same pass.
 */
static void ploytec_test_decode_permutation_complete(struct kunit *test)
{
	u8 src[PLOYTEC_CAPTURE_FRAME_SIZE];
	u8 dest[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	DECLARE_BITMAP(seen, PLOYTEC_CAPTURE_PCM_FRAME_SIZE * 8);
	int covered = 0;

	bitmap_zero(seen, PLOYTEC_CAPTURE_PCM_FRAME_SIZE * 8);

	for (int byte = 0; byte < PLOYTEC_CAPTURE_FRAME_SIZE; byte++) {
		for (int bit = 0; bit < 8; bit++) {
			bool meaningful = ploytec_capture_byte_used(byte) && bit < 3;
			int pos = -1, count, want_pos = -1;

			memset(src, 0, sizeof(src));
			src[byte] = 1 << bit;

			memset(dest, 0, sizeof(dest));
			ploytec_decode_batch(dest, src, 1);

			count = ploytec_count_set_bits(dest, sizeof(dest), &pos);

			if (!meaningful) {
				KUNIT_ASSERT_EQ_MSG(test, count, 0,
						    "wire byte %#04x bit %d is unused but changed the output",
						    byte, bit);
				continue;
			}

			KUNIT_ASSERT_EQ_MSG(test, count, 1,
					    "wire byte %#04x bit %d set %d output bits, expected 1",
					    byte, bit, count);

			for (size_t e = 0; e < ARRAY_SIZE(ploytec_decode_map); e++) {
				const struct ploytec_decode_map_entry *m =
					&ploytec_decode_map[e];

				if (m->src_bit == bit && byte >= m->src_base &&
				    byte < m->src_base + 8)
					want_pos = m->dst_idx * 8 +
						   (7 - (byte - m->src_base));
			}

			KUNIT_ASSERT_EQ_MSG(test, pos, want_pos,
					    "wire byte %#04x bit %d landed at output bit %d, map says %d",
					    byte, bit, pos, want_pos);
			KUNIT_ASSERT_FALSE_MSG(test, test_bit(pos, seen),
					       "output bit %d is written by two different wire bits",
					       pos);
			__set_bit(pos, seen);
			covered++;
		}
	}

	KUNIT_EXPECT_EQ(test, covered, PLOYTEC_CAPTURE_PCM_FRAME_SIZE * 8);
}

/* --- Linearity over GF(2) ------------------------------------------------- */

static void ploytec_test_encode_is_linear(struct kunit *test)
{
	u8 a[PLOYTEC_PLAYBACK_PCM_FRAME_SIZE], b[PLOYTEC_PLAYBACK_PCM_FRAME_SIZE];
	u8 ab[PLOYTEC_PLAYBACK_PCM_FRAME_SIZE];
	u8 ea[PLOYTEC_PLAYBACK_FRAME_SIZE], eb[PLOYTEC_PLAYBACK_FRAME_SIZE];
	u8 eab[PLOYTEC_PLAYBACK_FRAME_SIZE], want[PLOYTEC_PLAYBACK_FRAME_SIZE];
	struct ploytec_test_rng rng;

	ploytec_rng_init(&rng, 0xFEEDFACECAFEBEEFULL);

	for (int t = 0; t < PLOYTEC_TEST_LINEARITY_PAIRS; t++) {
		ploytec_rng_fill(&rng, a, sizeof(a));
		ploytec_rng_fill(&rng, b, sizeof(b));

		for (size_t i = 0; i < sizeof(ab); i++)
			ab[i] = a[i] ^ b[i];

		ploytec_encode_batch(ea, a, 1);
		ploytec_encode_batch(eb, b, 1);
		ploytec_encode_batch(eab, ab, 1);

		for (size_t i = 0; i < sizeof(want); i++)
			want[i] = ea[i] ^ eb[i];

		KUNIT_ASSERT_MEMEQ_MSG(test, eab, want, sizeof(want),
				       "encode(a^b) != encode(a)^encode(b) at iteration %d",
				       t);
	}
}

static void ploytec_test_decode_is_linear(struct kunit *test)
{
	u8 a[PLOYTEC_CAPTURE_FRAME_SIZE], b[PLOYTEC_CAPTURE_FRAME_SIZE];
	u8 ab[PLOYTEC_CAPTURE_FRAME_SIZE];
	u8 da[PLOYTEC_CAPTURE_PCM_FRAME_SIZE], db[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	u8 dab[PLOYTEC_CAPTURE_PCM_FRAME_SIZE], want[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	struct ploytec_test_rng rng;

	ploytec_rng_init(&rng, 0xFEEDFACECAFEBEEFULL);

	for (int t = 0; t < PLOYTEC_TEST_LINEARITY_PAIRS; t++) {
		ploytec_rng_fill(&rng, a, sizeof(a));
		ploytec_rng_fill(&rng, b, sizeof(b));

		for (size_t i = 0; i < sizeof(ab); i++)
			ab[i] = a[i] ^ b[i];

		ploytec_decode_batch(da, a, 1);
		ploytec_decode_batch(db, b, 1);
		ploytec_decode_batch(dab, ab, 1);

		for (size_t i = 0; i < sizeof(want); i++)
			want[i] = da[i] ^ db[i];

		KUNIT_ASSERT_MEMEQ_MSG(test, dab, want, sizeof(want),
				       "decode(a^b) != decode(a)^decode(b) at iteration %d",
				       t);
	}
}

/* --- Batching ------------------------------------------------------------- */

static void ploytec_test_encode_batch_equals_single(struct kunit *test)
{
	u8 src[PLOYTEC_TEST_MAX_ENCODE_FRAMES * PLOYTEC_PLAYBACK_PCM_FRAME_SIZE];
	u8 batched[PLOYTEC_TEST_MAX_ENCODE_FRAMES * PLOYTEC_PLAYBACK_FRAME_SIZE];
	u8 single[PLOYTEC_TEST_MAX_ENCODE_FRAMES * PLOYTEC_PLAYBACK_FRAME_SIZE];
	struct ploytec_test_rng rng;

	ploytec_rng_init(&rng, 0xD1CE0FF1CE0FF1CEULL);
	ploytec_rng_fill(&rng, src, sizeof(src));

	for (int n = 1; n <= PLOYTEC_TEST_MAX_ENCODE_FRAMES; n++) {
		memset(batched, 0, sizeof(batched));
		memset(single, 0, sizeof(single));

		ploytec_encode_batch(batched, src, n);

		for (int f = 0; f < n; f++)
			ploytec_encode_batch(single + f * PLOYTEC_PLAYBACK_FRAME_SIZE,
					     src + f * PLOYTEC_PLAYBACK_PCM_FRAME_SIZE,
					     1);

		KUNIT_EXPECT_MEMEQ_MSG(test, batched, single,
				       n * PLOYTEC_PLAYBACK_FRAME_SIZE,
				       "batch of %d differs from %d single-frame calls",
				       n, n);
	}
}

static void ploytec_test_decode_batch_equals_single(struct kunit *test)
{
	u8 src[PLOYTEC_TEST_MAX_DECODE_FRAMES * PLOYTEC_CAPTURE_FRAME_SIZE];
	u8 batched[PLOYTEC_TEST_MAX_DECODE_FRAMES * PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	u8 single[PLOYTEC_TEST_MAX_DECODE_FRAMES * PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	struct ploytec_test_rng rng;

	ploytec_rng_init(&rng, 0xD1CE0FF1CE0FF1CEULL);
	ploytec_rng_fill(&rng, src, sizeof(src));

	for (int n = 1; n <= PLOYTEC_TEST_MAX_DECODE_FRAMES; n++) {
		memset(batched, 0, sizeof(batched));
		memset(single, 0, sizeof(single));

		ploytec_decode_batch(batched, src, n);

		for (int f = 0; f < n; f++)
			ploytec_decode_batch(single + f * PLOYTEC_CAPTURE_PCM_FRAME_SIZE,
					     src + f * PLOYTEC_CAPTURE_FRAME_SIZE,
					     1);

		KUNIT_EXPECT_MEMEQ_MSG(test, batched, single,
				       n * PLOYTEC_CAPTURE_PCM_FRAME_SIZE,
				       "batch of %d differs from %d single-frame calls",
				       n, n);
	}
}

/*
 * jockey3.c computes the batch size from the ALSA ring-buffer wrap and can in
 * principle arrive at zero, so the codec must treat that as a no-op rather
 * than walking off the buffer.
 */
static void ploytec_test_encode_batch_zero_frames(struct kunit *test)
{
	u8 src[PLOYTEC_PLAYBACK_PCM_FRAME_SIZE] = { 0 };
	u8 dest[PLOYTEC_PLAYBACK_FRAME_SIZE];

	memset(dest, PLOYTEC_TEST_GUARD_BYTE, sizeof(dest));
	ploytec_encode_batch(dest, src, 0);

	for (size_t i = 0; i < sizeof(dest); i++)
		KUNIT_EXPECT_EQ_MSG(test, dest[i], PLOYTEC_TEST_GUARD_BYTE,
				    "encode of 0 frames wrote to dest[%zu]", i);
}

static void ploytec_test_decode_batch_zero_frames(struct kunit *test)
{
	u8 src[PLOYTEC_CAPTURE_FRAME_SIZE] = { 0 };
	u8 dest[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];

	memset(dest, PLOYTEC_TEST_GUARD_BYTE, sizeof(dest));
	ploytec_decode_batch(dest, src, 0);

	for (size_t i = 0; i < sizeof(dest); i++)
		KUNIT_EXPECT_EQ_MSG(test, dest[i], PLOYTEC_TEST_GUARD_BYTE,
				    "decode of 0 frames wrote to dest[%zu]", i);
}

static void ploytec_test_encode_batch_no_overrun(struct kunit *test)
{
	const size_t payload = PLOYTEC_TEST_MAX_ENCODE_FRAMES *
			       PLOYTEC_PLAYBACK_FRAME_SIZE;
	u8 src[PLOYTEC_TEST_MAX_ENCODE_FRAMES * PLOYTEC_PLAYBACK_PCM_FRAME_SIZE];
	struct ploytec_test_rng rng;
	u8 *buf;

	buf = kunit_kzalloc(test, payload + 2 * PLOYTEC_TEST_GUARD, GFP_KERNEL);
	KUNIT_ASSERT_NOT_NULL(test, buf);

	ploytec_rng_init(&rng, 0xBEEFCAFEBEEFCAFEULL);
	ploytec_rng_fill(&rng, src, sizeof(src));

	memset(buf, PLOYTEC_TEST_GUARD_BYTE, payload + 2 * PLOYTEC_TEST_GUARD);
	ploytec_encode_batch(buf + PLOYTEC_TEST_GUARD, src,
			     PLOYTEC_TEST_MAX_ENCODE_FRAMES);

	for (int i = 0; i < PLOYTEC_TEST_GUARD; i++) {
		KUNIT_EXPECT_EQ_MSG(test, buf[i], PLOYTEC_TEST_GUARD_BYTE,
				    "encode wrote %d bytes before the destination",
				    PLOYTEC_TEST_GUARD - i);
		KUNIT_EXPECT_EQ_MSG(test, buf[PLOYTEC_TEST_GUARD + payload + i],
				    PLOYTEC_TEST_GUARD_BYTE,
				    "encode wrote %d bytes past the destination",
				    i + 1);
	}
}

static void ploytec_test_decode_batch_no_overrun(struct kunit *test)
{
	const size_t payload = PLOYTEC_TEST_MAX_DECODE_FRAMES *
			       PLOYTEC_CAPTURE_PCM_FRAME_SIZE;
	u8 src[PLOYTEC_TEST_MAX_DECODE_FRAMES * PLOYTEC_CAPTURE_FRAME_SIZE];
	struct ploytec_test_rng rng;
	u8 *buf;

	buf = kunit_kzalloc(test, payload + 2 * PLOYTEC_TEST_GUARD, GFP_KERNEL);
	KUNIT_ASSERT_NOT_NULL(test, buf);

	ploytec_rng_init(&rng, 0xBEEFCAFEBEEFCAFEULL);
	ploytec_rng_fill(&rng, src, sizeof(src));

	memset(buf, PLOYTEC_TEST_GUARD_BYTE, payload + 2 * PLOYTEC_TEST_GUARD);
	ploytec_decode_batch(buf + PLOYTEC_TEST_GUARD, src,
			     PLOYTEC_TEST_MAX_DECODE_FRAMES);

	for (int i = 0; i < PLOYTEC_TEST_GUARD; i++) {
		KUNIT_EXPECT_EQ_MSG(test, buf[i], PLOYTEC_TEST_GUARD_BYTE,
				    "decode wrote %d bytes before the destination",
				    PLOYTEC_TEST_GUARD - i);
		KUNIT_EXPECT_EQ_MSG(test, buf[PLOYTEC_TEST_GUARD + payload + i],
				    PLOYTEC_TEST_GUARD_BYTE,
				    "decode wrote %d bytes past the destination",
				    i + 1);
	}
}

/* --- Alignment ------------------------------------------------------------ */

/*
 * The optimized codecs reach for 32- and 64-bit words through the unaligned
 * accessors. In the driver the wire buffer happens to be 8-byte aligned, so a
 * misuse of those accessors would go unnoticed on x86 and only surface as a
 * fault on a strict-alignment architecture. Run every byte offset explicitly.
 */
static void ploytec_test_encode_unaligned_buffers(struct kunit *test)
{
	u8 reference[PLOYTEC_PLAYBACK_FRAME_SIZE];
	u8 src[PLOYTEC_PLAYBACK_PCM_FRAME_SIZE];
	struct ploytec_test_rng rng;
	u8 *src_buf, *dst_buf;

	src_buf = kunit_kzalloc(test, PLOYTEC_PLAYBACK_PCM_FRAME_SIZE + 8, GFP_KERNEL);
	dst_buf = kunit_kzalloc(test, PLOYTEC_PLAYBACK_FRAME_SIZE + 8, GFP_KERNEL);
	KUNIT_ASSERT_NOT_NULL(test, src_buf);
	KUNIT_ASSERT_NOT_NULL(test, dst_buf);

	ploytec_rng_init(&rng, 0x1234ABCD5678EF90ULL);
	ploytec_rng_fill(&rng, src, sizeof(src));
	ploytec_oracle_encode(reference, src);

	for (int src_off = 0; src_off < 8; src_off++) {
		for (int dst_off = 0; dst_off < 8; dst_off++) {
			memcpy(src_buf + src_off, src, sizeof(src));
			memset(dst_buf, 0, PLOYTEC_PLAYBACK_FRAME_SIZE + 8);

			ploytec_encode_batch(dst_buf + dst_off, src_buf + src_off, 1);

			KUNIT_ASSERT_MEMEQ_MSG(test, dst_buf + dst_off, reference,
					       PLOYTEC_PLAYBACK_FRAME_SIZE,
					       "encode differs at src offset %d, dst offset %d",
					       src_off, dst_off);
		}
	}
}

static void ploytec_test_decode_unaligned_buffers(struct kunit *test)
{
	u8 reference[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	u8 src[PLOYTEC_CAPTURE_FRAME_SIZE];
	struct ploytec_test_rng rng;
	u8 *src_buf, *dst_buf;

	src_buf = kunit_kzalloc(test, PLOYTEC_CAPTURE_FRAME_SIZE + 8, GFP_KERNEL);
	dst_buf = kunit_kzalloc(test, PLOYTEC_CAPTURE_PCM_FRAME_SIZE + 8, GFP_KERNEL);
	KUNIT_ASSERT_NOT_NULL(test, src_buf);
	KUNIT_ASSERT_NOT_NULL(test, dst_buf);

	ploytec_rng_init(&rng, 0x1234ABCD5678EF90ULL);
	ploytec_rng_fill(&rng, src, sizeof(src));
	ploytec_oracle_decode(reference, src);

	for (int src_off = 0; src_off < 8; src_off++) {
		for (int dst_off = 0; dst_off < 8; dst_off++) {
			memcpy(src_buf + src_off, src, sizeof(src));
			memset(dst_buf, 0, PLOYTEC_CAPTURE_PCM_FRAME_SIZE + 8);

			ploytec_decode_batch(dst_buf + dst_off, src_buf + src_off, 1);

			KUNIT_ASSERT_MEMEQ_MSG(test, dst_buf + dst_off, reference,
					       PLOYTEC_CAPTURE_PCM_FRAME_SIZE,
					       "decode differs at src offset %d, dst offset %d",
					       src_off, dst_off);
		}
	}
}

/* --- Format invariants ---------------------------------------------------- */

static void ploytec_test_encode_zero_input(struct kunit *test)
{
	u8 src[PLOYTEC_PLAYBACK_PCM_FRAME_SIZE] = { 0 };
	u8 dest[PLOYTEC_PLAYBACK_FRAME_SIZE];
	u8 want[PLOYTEC_PLAYBACK_FRAME_SIZE] = { 0 };

	memset(dest, 0xFF, sizeof(dest));
	ploytec_encode_batch(dest, src, 1);

	KUNIT_EXPECT_MEMEQ_MSG(test, dest, want, sizeof(dest),
			       "silence did not encode to an all-zero wire frame");
}

/*
 * Playback packs only two channels into each wire byte, so bits 2..7 carry
 * nothing. jockey3.c relies on this: it writes the MIDI and sync bytes into
 * the same 512-byte packet and would be corrupted by a codec that spilled
 * into the upper bits.
 */
static void ploytec_test_encode_reserved_bits_clear(struct kunit *test)
{
	u8 src[PLOYTEC_PLAYBACK_PCM_FRAME_SIZE];
	u8 dest[PLOYTEC_PLAYBACK_FRAME_SIZE];
	struct ploytec_test_rng rng;

	ploytec_rng_init(&rng, 0x0F0F0F0FF0F0F0F0ULL);

	/* All ones is the worst case, then sample the space. */
	memset(src, 0xFF, sizeof(src));

	for (int t = 0; t < 256; t++) {
		memset(dest, 0, sizeof(dest));
		ploytec_encode_batch(dest, src, 1);

		for (size_t i = 0; i < sizeof(dest); i++)
			KUNIT_ASSERT_EQ_MSG(test, dest[i] & 0xFC, 0,
					    "wire byte %zu has reserved bits set (%#04x)",
					    i, dest[i]);

		ploytec_rng_fill(&rng, src, sizeof(src));
	}
}

static void ploytec_test_decode_ignores_unused_bytes(struct kunit *test)
{
	u8 src[PLOYTEC_CAPTURE_FRAME_SIZE];
	u8 probe[PLOYTEC_CAPTURE_FRAME_SIZE];
	u8 want[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	u8 got[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	struct ploytec_test_rng rng;

	ploytec_rng_init(&rng, 0xABCDEF0123456789ULL);
	ploytec_rng_fill(&rng, src, sizeof(src));
	ploytec_decode_batch(want, src, 1);

	for (int t = 0; t < 256; t++) {
		memcpy(probe, src, sizeof(probe));

		/* Scribble over everything the decoder should not be reading. */
		for (size_t i = 0; i < sizeof(probe); i++) {
			if (!ploytec_capture_byte_used(i))
				probe[i] = ploytec_rng_next(&rng) & 0xFF;
		}

		ploytec_decode_batch(got, probe, 1);
		KUNIT_ASSERT_MEMEQ_MSG(test, got, want, sizeof(want),
				       "decode result changed when unused wire bytes changed");
	}
}

static void ploytec_test_decode_ignores_unused_bits(struct kunit *test)
{
	u8 src[PLOYTEC_CAPTURE_FRAME_SIZE];
	u8 probe[PLOYTEC_CAPTURE_FRAME_SIZE];
	u8 want[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	u8 got[PLOYTEC_CAPTURE_PCM_FRAME_SIZE];
	struct ploytec_test_rng rng;

	ploytec_rng_init(&rng, 0x9988776655443322ULL);
	ploytec_rng_fill(&rng, src, sizeof(src));
	ploytec_decode_batch(want, src, 1);

	for (int t = 0; t < 256; t++) {
		/* Only bits 0..2 of each wire byte carry channel data. */
		for (size_t i = 0; i < sizeof(probe); i++)
			probe[i] = (src[i] & 0x07) |
				   (ploytec_rng_next(&rng) & 0xF8);

		ploytec_decode_batch(got, probe, 1);
		KUNIT_ASSERT_MEMEQ_MSG(test, got, want, sizeof(want),
				       "decode result changed when unused wire bits changed");
	}
}

/* --- Build wiring --------------------------------------------------------- */

/*
 * The three implementations are chosen by a preprocessor chain, and getting
 * that chain wrong silently selects the wrong codec. That is not theoretical:
 * the out-of-tree user-space harness built the 32-bit variant on x86_64 for
 * months because CONFIG_64BIT was not defined in its build.
 */
static void ploytec_test_codec_variant_matches_build(struct kunit *test)
{
	enum ploytec_codec_variant variant = ploytec_initialize_codec();

	if (IS_ENABLED(CONFIG_SND_USB_JOCKEY3_REFERENCE_CODEC))
		KUNIT_EXPECT_EQ_MSG(test, variant, PLOYTEC_CODEC_PORTABLE,
				    "REFERENCE_CODEC is set but the portable codec was not selected");
	else if (IS_ENABLED(CONFIG_64BIT))
		KUNIT_EXPECT_EQ_MSG(test, variant, PLOYTEC_CODEC_OPTIMIZED_64BIT,
				    "64-bit build did not select the 64-bit codec");
	else
		KUNIT_EXPECT_EQ_MSG(test, variant, PLOYTEC_CODEC_OPTIMIZED_32BIT,
				    "32-bit build did not select the 32-bit codec");
}

/* --- Suite ---------------------------------------------------------------- */

static int ploytec_codec_suite_init(struct kunit_suite *suite)
{
	/* Builds the bit-spread lookup tables the optimized codecs need. */
	ploytec_initialize_codec();

	return 0;
}

static struct kunit_case ploytec_codec_test_cases[] = {
	KUNIT_CASE_PARAM(ploytec_test_encode_known_vectors,
			 ploytec_encode_vector_gen_params),
	KUNIT_CASE_PARAM(ploytec_test_decode_known_vectors,
			 ploytec_decode_vector_gen_params),
	KUNIT_CASE(ploytec_test_encode_matches_oracle),
	KUNIT_CASE(ploytec_test_decode_matches_oracle),
	KUNIT_CASE(ploytec_test_encode_permutation_complete),
	KUNIT_CASE(ploytec_test_decode_permutation_complete),
	KUNIT_CASE(ploytec_test_encode_is_linear),
	KUNIT_CASE(ploytec_test_decode_is_linear),
	KUNIT_CASE(ploytec_test_encode_batch_equals_single),
	KUNIT_CASE(ploytec_test_decode_batch_equals_single),
	KUNIT_CASE(ploytec_test_encode_batch_zero_frames),
	KUNIT_CASE(ploytec_test_decode_batch_zero_frames),
	KUNIT_CASE(ploytec_test_encode_batch_no_overrun),
	KUNIT_CASE(ploytec_test_decode_batch_no_overrun),
	KUNIT_CASE(ploytec_test_encode_unaligned_buffers),
	KUNIT_CASE(ploytec_test_decode_unaligned_buffers),
	KUNIT_CASE(ploytec_test_encode_zero_input),
	KUNIT_CASE(ploytec_test_encode_reserved_bits_clear),
	KUNIT_CASE(ploytec_test_decode_ignores_unused_bytes),
	KUNIT_CASE(ploytec_test_decode_ignores_unused_bits),
	KUNIT_CASE(ploytec_test_codec_variant_matches_build),
	{},
};

static struct kunit_suite ploytec_codec_suite = {
	.name = "ploytec-codec",
	.suite_init = ploytec_codec_suite_init,
	.test_cases = ploytec_codec_test_cases,
};

kunit_test_suite(ploytec_codec_suite);
